[package]
name = "bevy-rpg"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.19.1"
bevy_common_assets = { version = "0.17.0", features = ["ron"] }
bevy_procedural_tilemaps = "0.4.0"
serde = { version = "1.0.229", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
