// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldConfig {
    pub id: u32,
    pub map_seed: u64,
    pub world_width: u32,
    pub world_height: u32,
}

impl __sdk::InModule for WorldConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `WorldConfig`.
///
/// Provides typed access to columns for query building.
pub struct WorldConfigCols {
    pub id: __sdk::__query_builder::Col<WorldConfig, u32>,
    pub map_seed: __sdk::__query_builder::Col<WorldConfig, u64>,
    pub world_width: __sdk::__query_builder::Col<WorldConfig, u32>,
    pub world_height: __sdk::__query_builder::Col<WorldConfig, u32>,
}

impl __sdk::__query_builder::HasCols for WorldConfig {
    type Cols = WorldConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        WorldConfigCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            map_seed: __sdk::__query_builder::Col::new(table_name, "map_seed"),
            world_width: __sdk::__query_builder::Col::new(table_name, "world_width"),
            world_height: __sdk::__query_builder::Col::new(table_name, "world_height"),
        }
    }
}

/// Indexed column accessor struct for the table `WorldConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct WorldConfigIxCols {
    pub id: __sdk::__query_builder::IxCol<WorldConfig, u32>,
}

impl __sdk::__query_builder::HasIxCols for WorldConfig {
    type IxCols = WorldConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        WorldConfigIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for WorldConfig {}
