// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::world_config_type::WorldConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `world_config`.
///
/// Obtain a handle from the [`WorldConfigTableAccess::world_config`] method on [`super::RemoteTables`],
/// like `ctx.db.world_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_config().on_insert(...)`.
pub struct WorldConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<WorldConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `world_config`.
pub struct WorldConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for WorldConfigTableAccessor {
    type Row = WorldConfig;
    type Handle<'db> = WorldConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.world_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `world_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait WorldConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`WorldConfigTableHandle`], which mediates access to the table `world_config`.
    fn world_config(&self) -> WorldConfigTableHandle<'_>;
}

impl WorldConfigTableAccess for super::RemoteTables {
    fn world_config(&self) -> WorldConfigTableHandle<'_> {
        WorldConfigTableHandle {
            imp: self.imp.get_table::<WorldConfig>("world_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct WorldConfigInsertCallbackId(__sdk::CallbackId);
pub struct WorldConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for WorldConfigTableHandle<'ctx> {
    type Row = WorldConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for WorldConfigTableHandle<'ctx> {
    type Row = WorldConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = WorldConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = WorldConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldConfigInsertCallbackId {
        WorldConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = WorldConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldConfigDeleteCallbackId {
        WorldConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for WorldConfigTableHandle<'ctx> {
    type InsertCallbackId = WorldConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldConfigInsertCallbackId {
        WorldConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: WorldConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for WorldConfigTableHandle<'ctx> {
    type DeleteCallbackId = WorldConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> WorldConfigDeleteCallbackId {
        WorldConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: WorldConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct WorldConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for WorldConfigTableHandle<'ctx> {
    type UpdateCallbackId = WorldConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldConfigUpdateCallbackId {
        WorldConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for WorldConfigTableHandle<'ctx> {
    type UpdateCallbackId = WorldConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> WorldConfigUpdateCallbackId {
        WorldConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: WorldConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `world_config`,
/// which allows point queries on the field of the same name
/// via the [`WorldConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.world_config().id().find(...)`.
pub struct WorldConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<WorldConfig, u32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> WorldConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `world_config`.
    pub fn id(&self) -> WorldConfigIdUnique<'ctx> {
        WorldConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> WorldConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u32) -> Option<WorldConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<WorldConfig>("world_config");
    _table.add_unique_constraint::<u32>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<WorldConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<WorldConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `WorldConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait world_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `WorldConfig`.
    fn world_config(&self) -> __sdk::__query_builder::Table<WorldConfig>;
}

impl world_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn world_config(&self) -> __sdk::__query_builder::Table<WorldConfig> {
        __sdk::__query_builder::Table::new("world_config")
    }
}
